# Generated by Django 5.1.6 on 2025-03-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emi_payment",
                    models.CharField(
                        choices=[("on_time", "On Time"), ("delayed", "Delayed")],
                        default="on_time",
                        max_length=10,
                    ),
                ),
                ("credit_usage", models.IntegerField()),
                ("credit_limit", models.IntegerField()),
                ("num_credit_cards", models.IntegerField()),
                (
                    "credit_mix",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced"),
                            ("unbalanced", "Unbalanced"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                ("hard_inquiries", models.IntegerField()),
                ("credit_history_years", models.IntegerField()),
                ("monthly_debt", models.IntegerField()),
                ("monthly_income", models.IntegerField()),
            ],
        ),
    ]
