# Generated by Django 5.1.6 on 2025-03-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emi_payment",
                    models.CharField(
                        choices=[("On-Time", "On-Time"), ("Delayed", "Delayed")],
                        max_length=10,
                    ),
                ),
                ("credit_usage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credit_limit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("num_credit_cards", models.IntegerField()),
                (
                    "credit_mix",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced"),
                            ("unbalanced", "Unbalanced"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hard_inquiries", models.IntegerField()),
                ("credit_history", models.IntegerField()),
                ("monthly_debt", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("credit_score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CreditProfile",
        ),
    ]
